FROM mhart/alpine-node:11 AS builder
RUN apk update
WORKDIR /tmp
ADD package.json /tmp/
ADD package-lock.json /tmp/

RUN npm install --no-save

ENV REACT_APP_TENANT_NAME $REACT_APP_TENANT_NAME

ADD . /code/
WORKDIR /code
RUN cp -a /tmp/node_modules /code/node_modules

WORKDIR /code
CMD ["npm", "start"]

# docker rmi -f $(docker images | grep "frontend" | awk '{print $3}') # remove all <none> images
